name: phpstan

on:
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ "8.0", "8.1" ]
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mongodb, sodium
          tools: composer:v2

      - name: Prepare
        run: composer install

      - name: Versions
        run: |
          cat /etc/os-release
          php -v
          ./vendor/bin/phpstan --version
      - name: Execute php-cs-fixer
        run: |
          ./vendor/bin/phpstan analyse
